/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankTransferIndexRouteImport } from './routes/bank-transfer/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankTransferIndexRoute = BankTransferIndexRouteImport.update({
  id: '/bank-transfer/',
  path: '/bank-transfer/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank-transfer': typeof BankTransferIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank-transfer': typeof BankTransferIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank-transfer/': typeof BankTransferIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bank-transfer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bank-transfer'
  id: '__root__' | '/' | '/bank-transfer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankTransferIndexRoute: typeof BankTransferIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-transfer/': {
      id: '/bank-transfer/'
      path: '/bank-transfer'
      fullPath: '/bank-transfer'
      preLoaderRoute: typeof BankTransferIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankTransferIndexRoute: BankTransferIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
